### ISSUE TITLE
WebServer returning 403 and 404 Errors

### ISSUE THREAD

**Issue by sergio-caro** [limtaesu/alloworigin#15]
I don't know if it is about the *instability* of the test server, but the Server is not working at all.

Accessing the Server (http://alloworigin.com/) returns *403 Forbiden* and making requests (http://alloworigin.com/get?url=http://example.com) returns *404 Not Found*.

Capture:
![captura](https://cloud.githubusercontent.com/assets/10022678/12648655/4acd7f94-c5db-11e5-8c3a-104032ba71d5.PNG)

**Comment by limtaesu** [comment]
should be back up now. my dedicated server was rebooted, nginx started and took over, when I am using apache2

**Comment by sergio-caro** [comment]
Yep, Thanks bro :+1:
