### ISSUE TITLE
make the domain accessible over ssl/https

### ISSUE THREAD

**Issue by marcules** [limtaesu/alloworigin#7]
Hi there,
can you set up a free valid SSL certificate through for example https://www.startssl.com/ and make the domain accessible over https://alloworigin.com ?

**Comment by limtaesu** [comment]
sure.
I was thinking putting it behind cloudflare which gives it free https.

**Comment by marcules** [comment]
I didn't know they provided https for free. Not sure about others, but I don't care if it goes through cloudflare (there are people with privacy concerns regarding cloudflare though).

Nevertheless I used https://allow-any-origin.appspot.com/ for now, but your serivce is currently more stable (and does not require a XMLHttpRequest Version 2), and I'll be switching back as soon as possible :D

**Comment by limtaesu** [comment]
https://alloworigin.com/ up and running.
