### ISSUE TITLE
Redirect loop

### ISSUE THREAD

**Issue by Shadowen** [limtaesu/alloworigin#8]
I may have put your server into a redirect loop by pointing it's `get?url=` parameter back at itself. Server is returning 522 to all requests. Hopefully a reboot can fix the issue.
I will take a look at the code to see if I can isolate the problem/put together a fix.
I have been getting a lot of server (timeouts) in general since I started using the server, but I guess that's to be expected. Thanks for letting me try the service out.

**Comment by limtaesu** [comment]
Hey, I have restarted the server.
Guess I have to block the service to call itself.
PR welcomed!

**Comment by Shadowen** [comment]
Awesome, thanks!
I'm only using the service for development purposes, so don't worry about (any) demand. It's the first time I've come across this cross-origin issue and it really sucks. If I ever produce something I'll probably host my own fork.
Unfortunately my webserver is limited to PHP rather than Python, so I might be leaning towards that kind of solution...
